# Site settings
title: DaulPav.id
tagline:
  Cybersecurity, Programming, Signal Processing

# Personal information
author:
  name: DaulPavid
  email: daulpavid@daulpav.id
  github: daulpavid
  mastodon_instance: infosec.exchange
  mastodon_handle: daulpavid
  linkedin: daulpavid

darkhack:
  date_format: "%x"
  font_awesome: "357d91f838"

remote_theme: daulpavid/darkhack
